name: Hidden Untrusted Checkout Exec - Ref
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash hidden.sh
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
