name: Injection - Pr Title
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

permissions: {}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.TITLE }}
        env:
          TITLE: ${{ github.event.pull_request.title }}
