name: Hidden Untrusted Checkout Exec - Ref
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

permissions:
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
