name: Hidden Untrusted Checkout Exec - Ref
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

permissions:
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - run: bash hidden.sh
        env:
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
