name: Untrusted Checkout Exec - SHA
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: bash script.sh
