name: Untrusted Checkout Exec - Ref
on:
  pull_request_target:

env:
  FLAG: ${{ secrets.FLAG }}

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: bash script.sh
